spring:
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 30s # default
  #profiles:
  #  active: local
server:
  port: 8080 # default
  shutdown: graceful # default since 3.4
management:
  server:
    port: 8081 # default
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,shutdown
grpc:
  server:
    port: 9090 # default
