spring:
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 30s # default
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    hikari:
      minimum-idle: 10 # default
      maximum-pool-size: 10 # default
      auto-commit: false
server:
  port: 8080 # default
  shutdown: graceful # default since 3.4
management:
  server:
    port: 8081 # default
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,shutdown
grpc:
  server:
    port: 9090 # default
