spring:
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 10s
server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
management:
  server:
    port: 8081
grpc:
  server:
    port: 9090
app.log.appender: console-text
